### ISSUE TITLE
NPE (JMeter-CCFinder)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#15]
Clone #43 (Group 1462, Pair 1-2): org.apache.jmeter.JMeter#startGui (row 111) and org.apache.jmeter.JMeterReport#startGui (row 112)

```
java.lang.NullPointerException
    at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.findPassedParameters(PreconditionExaminer.java:594)
    at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.<init>(PreconditionExaminer.java:288)
    at gr.uom.java.ast.decomposition.cfg.mapping.PDGRegionSubTreeMapper.<init>(PDGRegionSubTreeMapper.java:40)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.getOptimalSolution(Application.java:1116)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:608)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:180)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [2b6bf17c47e32115aaabe76daace6d2469ee4676](https://github.com/tsantalis/JDeodorant/commit/2b6bf17c47e32115aaabe76daace6d2469ee4676)
