### ISSUE TITLE
NPE (Ant-CCFinder)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#17]
Clone # 5 (Group 113, Pair 1-2): org.apache.tools.ant.taskdefs.optional.javacc.JJTree#execute (row 46) and org.apache.tools.ant.taskdefs.optional.javacc.JJDoc#execute (row 47)

```
java.lang.NullPointerException
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.replaceExpression(ExtractCloneRefactoring.java:3697)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.processASTNodeWithDifferences(ExtractCloneRefactoring.java:3322)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.processCloneStructureNode(ExtractCloneRefactoring.java:2582)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.extractClone(ExtractCloneRefactoring.java:1160)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.apply(ExtractCloneRefactoring.java:327)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.checkFinalConditions(ExtractCloneRefactoring.java:4484)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:626)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:180)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commits
[8ff6f77233594bfabe978d6827d700a95b397deb](https://github.com/tsantalis/JDeodorant/commit/8ff6f77233594bfabe978d6827d700a95b397deb)
and
[fcb4db6c62ef4742fc1c40974eedab3e0ad32a2a](https://github.com/tsantalis/JDeodorant/commit/fcb4db6c62ef4742fc1c40974eedab3e0ad32a2a)
