### ISSUE TITLE
NPE (JEdit-NiCad Consistent)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#18]
Clone # 11 (Group 11, Pair 1-2): gnu.regexp.REFilterInputStream#read (row 22) and gnu.regexp.REFilterReader#read (row 23)

```
java.lang.NullPointerException
    at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.findReturnTypeBinding(PreconditionExaminer.java:3767)
    at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.getReturnTypeBinding(PreconditionExaminer.java:3709)
    at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.checkIfAllPossibleExecutionFlowsEndInReturn(PreconditionExaminer.java:1797)
    at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.<init>(PreconditionExaminer.java:364)
    at gr.uom.java.ast.decomposition.cfg.mapping.PDGRegionSubTreeMapper.<init>(PDGRegionSubTreeMapper.java:40)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.getOptimalSolution(Application.java:1282)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:608)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:180)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [8704926aceaeafaac6bfee2b5617771366dd5303](https://github.com/tsantalis/JDeodorant/commit/8704926aceaeafaac6bfee2b5617771366dd5303)
