### ISSUE TITLE
IllegalArgumentException (JRuby-CCFinder)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#19]
Clone # 20 (Group 360, Pair 1-2): org.jruby.javasupport.JavaClass#declared_method (row 76) and org.jruby.javasupport.JavaClass#java_method (row 77) 

```
java.lang.IllegalArgumentException
    at org.eclipse.jdt.core.dom.rewrite.ListRewrite.insertLast(ListRewrite.java:249)
    at gr.uom.java.jdeodorant.refactoring.manipulators.RefactoringUtility.createParameterizedType(RefactoringUtility.java:121)
    at gr.uom.java.jdeodorant.refactoring.manipulators.RefactoringUtility.generateTypeFromTypeBinding(RefactoringUtility.java:76)
    at gr.uom.java.jdeodorant.refactoring.manipulators.RefactoringUtility.generateTypeFromTypeBinding(RefactoringUtility.java:109)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoringGapHandler.createFunctionalInterface(ExtractCloneRefactoringGapHandler.java:256)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoringGapHandler.createInterfaceType(ExtractCloneRefactoringGapHandler.java:1100)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoringGapHandler.createParameterType(ExtractCloneRefactoringGapHandler.java:1109)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.extractClone(ExtractCloneRefactoring.java:1278)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.apply(ExtractCloneRefactoring.java:327)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.checkFinalConditions(ExtractCloneRefactoring.java:4484)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:626)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:180)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [bc485130ded35002a3747b91fdec9c527878419c](https://github.com/tsantalis/JDeodorant/commit/bc485130ded35002a3747b91fdec9c527878419c)
