### ISSUE TITLE
NPE (Columba-Deckard)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#20]
Clone # 28 (Group 100, Pair 1-2): org.columba.mail.folder.command.CreateFilterOnMessageCommand#execute (row 62) and org.columba.mail.folder.command.CreateVFolderOnMessageCommand#execute (row 63)

```
java.lang.NullPointerException
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoringGapHandler.createLambdaExpressionForBlockGap(ExtractCloneRefactoringGapHandler.java:592)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.modifySourceMethod(ExtractCloneRefactoring.java:4084)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.apply(ExtractCloneRefactoring.java:338)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.checkFinalConditions(ExtractCloneRefactoring.java:4484)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:626)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:180)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [2ca1d078c70c88bf0df69bb9c80e87302b1752be](https://github.com/tsantalis/JDeodorant/commit/2ca1d078c70c88bf0df69bb9c80e87302b1752be)
