### ISSUE TITLE
NPE (JRuby-NiCad Blind)

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/JDeodorant#24]
Clone #446 (Group 446, Pair 1-2): org.jruby.test.bench.BenchLongFibRecursive#boxedLongFib (row 1499) and org.jruby.test.bench.BenchIntFibRecursive#integerFib (row 1500)

```
 java.lang.NullPointerException
at gr.uom.java.ast.decomposition.matching.ASTNodeMatcher.commonSuperType(ASTNodeMatcher.java:479)
at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.findReturnTypeBinding(PreconditionExaminer.java:3774)
at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.getReturnTypeBinding(PreconditionExaminer.java:3709)
at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.checkIfAllPossibleExecutionFlowsEndInReturn(PreconditionExaminer.java:1797)
at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.<init>(PreconditionExaminer.java:364)
at gr.uom.java.ast.decomposition.cfg.mapping.PDGRegionSubTreeMapper.<init>(PDGRegionSubTreeMapper.java:40)
at ca.concordia.jdeodorant.eclipse.commandline.Application.getOptimalSolution(Application.java:1630)
at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:820)
at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:210)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [792365f2fd19a2aad64ce6359b81e91960c587e0](https://github.com/tsantalis/JDeodorant/commit/792365f2fd19a2aad64ce6359b81e91960c587e0)
