### ISSUE TITLE
NoSuchElementException (Hibernate-NiCad)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#28]
Clone # 321 (Group 321, Pair 1-4): org.hibernate.cache.jbc2.builder.MultiplexingCacheInstanceManager#releaseCaches (row 993) and org.hibernate.cache.jbc2.builder.MultiplexingCacheInstanceManager#releaseCaches (row 996)

```
java.util.NoSuchElementException
    at java.util.TreeMap.key(TreeMap.java:1327)
    at java.util.TreeMap.firstKey(TreeMap.java:290)
    at java.util.TreeSet.first(TreeSet.java:394)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.modifySourceMethod(ExtractCloneRefactoring.java:4148)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.apply(ExtractCloneRefactoring.java:338)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.checkFinalConditions(ExtractCloneRefactoring.java:4500)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:626)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:180)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [627e87d1895d2d8a33bfea7c54b63c5abddbdbde](https://github.com/tsantalis/JDeodorant/commit/627e87d1895d2d8a33bfea7c54b63c5abddbdbde)
