### ISSUE TITLE
IllegalArgumentException (EMF-CloneDR)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#45]
Clone # 339 (Group 339, Pair 1-2): org.eclipse.emf.common.util.BasicEList#getNonDuplicates (row 2253) and org.eclipse.emf.common.util.DelegatingEList#getNonDuplicates (row 2254)

```
java.lang.IllegalArgumentException: Invalid identifier : >IntermediateAbstractList<E><
    at org.eclipse.jdt.core.dom.SimpleName.setIdentifier(SimpleName.java:199)
    at org.eclipse.jdt.core.dom.AST.newSimpleName(AST.java:2202)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.extractClone(ExtractCloneRefactoring.java:633)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.apply(ExtractCloneRefactoring.java:336)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.checkFinalConditions(ExtractCloneRefactoring.java:4974)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:669)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:185)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [af4366ced91b10013925f147ab8f18b67a3f18e8](https://github.com/tsantalis/JDeodorant/commit/af4366ced91b10013925f147ab8f18b67a3f18e8)
