### ISSUE TITLE
IllegalArgumentException (EMF-CloneDR)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#48]
Group 1294, Pair 1-3: org.eclipse.emf.edit.provider.ItemProvider#getElements (row 4755) and org.eclipse.emf.edit.provider.WrapperItemProvider#getElements (row 4757)

```
java.lang.IllegalArgumentException
    at org.eclipse.jdt.core.dom.rewrite.ListRewrite.insertLast(ListRewrite.java:249)
    at gr.uom.java.jdeodorant.refactoring.manipulators.RefactoringUtility.createParameterizedType(RefactoringUtility.java:150)
    at gr.uom.java.jdeodorant.refactoring.manipulators.RefactoringUtility.generateTypeFromTypeBinding(RefactoringUtility.java:91)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.extractClone(ExtractCloneRefactoring.java:1080)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.apply(ExtractCloneRefactoring.java:340)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.checkFinalConditions(ExtractCloneRefactoring.java:5041)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:669)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:185)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [b33209ee65187d45488af088acb0f136b641deed](https://github.com/tsantalis/JDeodorant/commit/b33209ee65187d45488af088acb0f136b641deed)
