### ISSUE TITLE
NPE (JEdit-CCFinder)

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#51]
Clone # 72 (Group 320, Pair 1-2): org.gjt.sp.jedit.options.ToolBarOptionPane#actionPerformed (row 290) and org.gjt.sp.jedit.options.ToolBarOptionPane#ToolBarEditDialog (row 291)

```
java.lang.NullPointerException
    at gr.uom.java.ast.decomposition.cfg.mapping.PreconditionExaminer.isTemplateMethodApplicable(PreconditionExaminer.java:3376)
    at gr.uom.java.ast.decomposition.cfg.mapping.DivideAndConquerMatcher.isTemplateMethodApplicable(DivideAndConquerMatcher.java:274)
    at ca.concordia.jdeodorant.eclipse.commandline.cloneinfowriter.CloneInfoCSVWriter.writeCloneInfo(CloneInfoCSVWriter.java:105)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:765)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:185)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tsantalis** [comment]
Fixed in commit [0b2fbf672af2cc211f0922f3fd3cd8ace891e3ea](https://github.com/tsantalis/JDeodorant/commit/0b2fbf672af2cc211f0922f3fd3cd8ace891e3ea)
