### ISSUE TITLE
NullPointerException in ControlDependenceTreeNode

### ISSUE THREAD

**Issue by alwaqfi** [tsantalis/JDeodorant#58]
Hi,

I am getting the error below when I am trying to test case 117 Apache Ant - Deckard (TSE paper test set).

08:19:16.597 [main] INFO  c.c.j.e.commandline.Application - 15%: Reading information from row 265 (Clone group ID 117, clone 2)
08:19:16.606 [main] INFO  c.c.j.e.commandline.Application - 15%: Generating PDG for method "toString" in "org.apache.tools.ant.types.selectors.PresentSelector"
08:19:16.616 [main] INFO  c.c.j.e.commandline.Application - 15%: Analyzing Clone 117 (Group 117, Pair 1-2): org.apache.tools.ant.types.selectors.DependSelector#toString (row 264) and org.apache.tools.ant.types.selectors.PresentSelector#toString (row 265)
08:19:16.634 [main] INFO  c.c.j.e.commandline.Application - CDT 1 depth = 1, CDT 2 depth = 1
08:19:16.634 [main] INFO  c.c.j.e.commandline.Application - CDT 1 leaves = 4, CDT 2 leaves = 6
08:19:16.635 [main] INFO  c.c.j.e.commandline.Application - Start mapping
java.lang.NullPointerException
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.getId(ControlDependenceTreeNode.java:427)
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.getNode(ControlDependenceTreeNode.java:84)
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.getNode(ControlDependenceTreeNode.java:92)
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.parentChildRelationship(ControlDependenceTreeNode.java:62)
    at gr.uom.java.ast.decomposition.cfg.mapping.DivideAndConquerMatcher.matchBasedOnControlDependenceTreeStructure(DivideAndConquerMatcher.java:870)
    at gr.uom.java.ast.decomposition.cfg.mapping.PDGRegionSubTreeMapper.<init>(PDGRegionSubTreeMapper.java:38)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.getOptimalSolution(Application.java:1740)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:892)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:208)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

Thanks,
Asif

**Comment by tsantalis** [comment]
Unable to replicate the NullPointerException. This case is refactorable with Lambda expressions.
I am attaching the generated HTML report
[117-1-2.zip](https://github.com/tsantalis/JDeodorant/files/522606/117-1-2.zip)
