### ISSUE TITLE
NullPointerException in ControlDependenceTreeNode.getId

### ISSUE THREAD

**Issue by alwaqfi** [tsantalis/JDeodorant#59]
Hi,

I am getting the error below in ApacheAnt-Deckard case 117.

Regards,
Asif

---

java.lang.NullPointerException
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.getId(ControlDependenceTreeNode.java:427)
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.getNode(ControlDependenceTreeNode.java:84)
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.getNode(ControlDependenceTreeNode.java:92)
    at gr.uom.java.ast.decomposition.cfg.mapping.ControlDependenceTreeNode.parentChildRelationship(ControlDependenceTreeNode.java:62)
    at gr.uom.java.ast.decomposition.cfg.mapping.DivideAndConquerMatcher.matchBasedOnControlDependenceTreeStructure(DivideAndConquerMatcher.java:870)
    at gr.uom.java.ast.decomposition.cfg.mapping.PDGRegionSubTreeMapper.<init>(PDGRegionSubTreeMapper.java:38)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.getOptimalSolution(Application.java:1733)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:885)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:208)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by tsantalis** [comment]
The exception cannot be replicated.
