### ISSUE TITLE
Cannot start identify process

### ISSUE THREAD

**Issue by mferretti** [tsantalis/JDeodorant#84]
Hi, 
I am trying JDeodorant for the 1st time on Eclipse IDE Version: 2021-03 (4.19.0).
Installation goes down smoothly, but I cannot start the "identify bad smell" process for any "Bad Smell" menu entry. As an example, on the "Long Method" tab, when I try to run the process, I get: 
```

java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
	at org.eclipse.ui.internal.progress.ProgressMonitorJobsDialog.run(ProgressMonitorJobsDialog.java:228)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$26(ProgressManager.java:821)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.progress.ProgressManager.busyCursorWhile(ProgressManager.java:854)
	at org.eclipse.ui.internal.progress.ProgressManager.busyCursorWhile(ProgressManager.java:830)
	at gr.uom.java.jdeodorant.refactoring.views.LongMethod.getTable(LongMethod.java:696)
	at gr.uom.java.jdeodorant.refactoring.views.LongMethod.access$14(LongMethod.java:687)
	at gr.uom.java.jdeodorant.refactoring.views.LongMethod$4.run(LongMethod.java:477)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
Caused by: java.lang.ClassCastException: class org.eclipse.jdt.core.dom.SimpleName cannot be cast to class org.eclipse.jdt.core.dom.Statement (org.eclipse.jdt.core.dom.SimpleName and org.eclipse.jdt.core.dom.Statement are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @23707d5d)
	at gr.uom.java.ast.decomposition.AbstractStatement.getStatement(AbstractStatement.java:22)
	at gr.uom.java.ast.MethodObject.isGetter(MethodObject.java:141)
	at gr.uom.java.ast.ASTReader.processMethodDeclaration(ASTReader.java:590)
	at gr.uom.java.ast.ASTReader.processTypeDeclaration(ASTReader.java:376)
	at gr.uom.java.ast.ASTReader.parseAST(ASTReader.java:259)
	at gr.uom.java.ast.ASTReader.parseAST(ASTReader.java:235)
	at gr.uom.java.ast.ASTReader.<init>(ASTReader.java:89)
	at gr.uom.java.jdeodorant.refactoring.views.LongMethod$9.run(LongMethod.java:699)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
After that error, no process starts, and no log/exception is thrown.

**Comment by tsantalis** [comment]
@mferretti 
Is it possible to share the source code of the project on which you executed JDeodorant?
The exception is related with the analysis of the source code.

Thank you.

**Comment by mferretti** [comment]
Hi
I will have to ask. In the meantime: the project is a maven master/child project, with a "commons" utility project, two EJB projects with JPA, and one JSF WAR. CDI is used throughout the whole code
I have tried to start the analysis on the commons child project: will ask to share that
